version: '3'

services:
  redis:
    image: redis
    ports:
      - "6380:6379"
  interdb-hub:
    build:
      context: .
    links:
      - redis
    environment:
      - HUB_REDIS_HOST=redis
      - HUB_REDIS_PORT=6380
    ports:
      - "12000:80"